name: Test and build demo

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CECIL_BASEURL: https://cecilapp.github.io/theme-applanding/
      CECIL_CANONICALURL: true
    steps:
      - name: Download Cecil
        run: |
          curl -sSOL https://cecil.app/cecil.phar
          php cecil.phar --version

      - name: Create site
        run: |
          php cecil.phar new:site -n
          rm ./pages/index.md
          cat > ./pages/index.md <<EOF
          ---
          title: App Landing theme
          ---
          This is a demo of the _App Landing_ theme.
          EOF

      - name: Install theme
        uses: actions/checkout@v4
        with:
          path: ./themes/applanding

      - name: Add theme to configuration file
        run: |
          echo -e "theme:\n  - applanding" >> ./config.yml
          rm -rf ./layouts

      - name: Add theme config
        run: |
          cat >> ./config.yml <<EOF
          applanding:
            buttons:
              - name: Netlify
                url: https://cecil.app/hosting/netlify/deploy
                image: https://www.netlify.com/img/deploy/button.svg
            source: https://github.com/Cecilapp/the-butler
            documentation: https://github.com/Cecilapp/the-butler#readme
            demo: https://the-butler-demo.cecil.app
            screenshot: https://the-butler.cecil.app/cecil-preview.e39f27ed3641fa0022e6ee1711472086.png
          EOF

      - name: Add Tailwind config
        run: |
          cat > ./tailwind.config.js <<EOF
          module.exports = {
            presets: [
              require('./themes/applanding/tailwind.preset.js')
            ],
            content: [
              './layouts/**/*.html.twig',
              './themes/**/layouts/**/*.html.twig',
            ]
          }
          EOF

      - name: Build CSS with Tailwind
        run: |
          npm install -D tailwindcss
          npx tailwindcss -i ./themes/applanding/tailwind.css -o ./assets/styles.css

      #- uses: actions/upload-artifact@v3
      #  with:
      #    name: debug
      #    path: ./

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build site
        run: php cecil.phar build -vv

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
